name: Build PR From Fork

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: | # check if PR opened from fork
      github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name || contains(github.head_ref, 'dependabot')
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          persist-credentials: false

      - name: Build App
        uses: ./.github/actions/build
        with:
          NEXT_PUBLIC_ENV: "prod"

      - name: Upload artifacts
        uses: ./.github/actions/upload-artifacts
