name: Upload Crowdin files

# on any push to main, we upload the translations to be translated
on:
  push:
    branches:
      - main

jobs:
  upload-to-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Synchronize
        uses: crowdin/github-action@6db87d404b6a13cd118070f9af29957aa47ee1f3 # v1.5.2
        with:
          upload_sources: true
          download_translations: false
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
